name: Build Common

on:
  workflow_call:
    inputs:
      device:
        required: true
        type: string
      prefix:
        required: false
        type: string
    secrets:
      repo:
        required: true
      ssh_key:
        required: true
      chat_id:
        required: true
      TELEGRAM_BOT_TOKEN:
        required: true
      TELEGRAM_SAVE_FILE:
        required: true

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        device: ${{ fromJson(inputs.device) }}
        ksu: [ _ksu, "" ]
        susfs: [ _susfs, "" ]
        debug: [ "", _permissivedebug ]
        exclude:
          - ksu: ""
            susfs: _susfs
          - ksu: ""
            debug: _permissivedebug
          - susfs: ""
            debug: _permissivedebug

    name: "DEVICE=${{ matrix.device }} KSU=${{ matrix.ksu }} SUSFS=${{ matrix.susfs }} DEBUG=${{ matrix.debug }}"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.repo }}
          ref: ${{ vars.BRANCH }}
          ssh-key: ${{ secrets.ssh_key }}
          fetch-depth: 1
          path: repo
          persist-credentials: false

      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get install -y bison flex libssl-dev python3 python-is-python3 libarchive-tools zstd make unzip zip

          echo "ARCH=arm64" >> $GITHUB_ENV
          echo "PLATFORM_VERSION=12" >> $GITHUB_ENV
          echo "ANDROID_MAJOR_VERSION=s" >> $GITHUB_ENV
          echo "LLVM=1" >> $GITHUB_ENV
          echo "KBUILD_BUILD_USER=Long" >> $GITHUB_ENV
          echo "KBUILD_BUILD_HOST=Long-CI" >> $GITHUB_ENV
          echo "TIME=$(date +%Y%m%d)" >> $GITHUB_ENV

      - name: Setup toolchain & KernelSU
        run: |
          cd repo

          if [ "${{ matrix.susfs }}" = "" ]; then
            git clone --depth=1 -b v1.1.1 https://github.com/longuirom/KernelSU-Next KernelSU
          else
            git clone --depth=1 -b v1.1.1-susfs1.5.11 https://github.com/longuirom/KernelSU-Next KernelSU
          fi

          mkdir -p "$HOME/toolchains/neutron-clang"
          cd "$HOME/toolchains/neutron-clang"
          bash <(curl -s "https://raw.githubusercontent.com/Neutron-Toolchains/antman/main/antman") -S
          echo "$HOME/toolchains/neutron-clang/bin" >> $GITHUB_PATH

      - name: Build kernel
        run: |
          cd repo

          if [ "${{ matrix.debug }}" = "_permissivedebug" ]; then
            scripts/kconfig/merge_config.sh arch/arm64/configs/exynos9610-${{ matrix.device }}_defconfig arch/arm64/configs/debug_defconfig
            make olddefconfig
          else
            make exynos9610-${{ matrix.device }}_defconfig
          fi

          if [ "${{ matrix.ksu }}" = "" ]; then
            scripts/config -d CONFIG_KSU
          else
            if [ "${{ matrix.susfs }}" = "" ]; then
              scripts/config -d CONFIG_KSU_SUSFS
            else
              scripts/config -d CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT
            fi
          fi

          make -j$(nproc)

      - name: Package AnyKernel3
        run: |
          cd repo
          git clone --depth=1 https://github.com/longuirom/AnyKernel3
          cp arch/arm64/boot/Image AnyKernel3/

          OUT_NAME="LONG_${{ matrix.device }}_${{ env.TIME }}${{ matrix.ksu }}${{ matrix.susfs }}${{ matrix.debug }}${{ inputs.prefix }}"

          cd AnyKernel3
          zip -r "${OUT_NAME}.zip" ./*
          cd ..
          cp "AnyKernel3/${OUT_NAME}.zip" ./

          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendDocument" \
          -F chat_id=${{ secrets.chat_id }} \
          -F document=@${OUT_NAME}.zip -o response.json

          curl -X POST "${{ secrets.TELEGRAM_SAVE_FILE }}" \
          -H "Content-Type: application/json" \
          -d @response.json
