name: test-a51xx

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        device: [ a51xx ]
        ksu: [ _ksu, "" ]
        susfs: [ _susfs, "" ]
        debug: [ _permissivedebug, "" ]
        exclude:
          - ksu: ""
            susfs: _susfs
          - ksu: ""
            debug: _permissivedebug

    uses: ./.github/workflows/build-common.yml
    with:
      device: ${{ matrix.device }}
      ksu: ${{ matrix.ksu }}
      susfs: ${{ matrix.susfs }}
      debug: ${{ matrix.debug }}
      chat_id: ${{ secrets.TELEGRAM_CHAT_ID_TEST }}
      prefix: "_test"
